spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_store # Database URL.
    username: pet_store # Database username.
    password: pet_store # Database password.
  jpa:
    hibernate:
      ddl-auto: update # Tells Hibernate to automatically update the database schema.
    show-sql: true # Enables SQL query logging.
  
  
  
